name: Publish the docs

on:
  push:
    branches:
      - 6.x
      - 6.dev

jobs:
  build:
    name: Build the HTML
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM and build
        run: |
          npm install
          npm run build

      - name: Zip the docs
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r EEDocs6.latest.zip build

      - name: Move the zip
        run: |
          ls -latr
          mkdir build/downloads
          mv EEDocs6.latest.zip build/downloads/EEDocs6.latest.zip

      - name: Rsync to Staging
        if: github.base_ref == '6.dev'
        uses: Burnett01/rsync-deployments@5.1
        with:
          switches: -avz
          path: build/
          remote_path: ${{ secrets.DOCS_PATH_STAGING }}/v6
          remote_host: ${{ secrets.DOCS_HOST_STAGING }}
          remote_user: ${{ secrets.DOCS_USER }}
          remote_key: ${{ secrets.DOCS_USER_ID_RSA }}
